name: Auto Assign New issues to Project

on:
  issues:
    types:
      - opened
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: |-
           gh api graphql -F contentId=$ISSUE_ID -F projectId=$PROJECT_ID -f query='
             mutation($projectId: ID!, $contentId: ID!) {
               addProjectV2ItemById(input: {projectId: $projectId contentId: $contentId}) {
                 item {
                   id
                 }
             }
           }'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_ID: ${{ github.event.issue.node_id }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
